### ISSUE TITLE
Unable to parse JSON files

### ISSUE THREAD

**Issue by KindarConrath** [AgriCraft/agricraft.github.io#1]
Updated to 2.0.0-0.4.0-a5, all seeds disappeared from JEI, seeds in chests turned into "Generic Seeds" 

Error messages appeared in the logs about being unable to parse the JSON files. 

I deleted the files and let them be rebuilt, and that appears to have fixed it.

**Comment by InfinityRaider** [comment]
Yes, expect this to happen quite some more times between alpha releases as internals are changing. It's quite inconvenient, but the alpha builds are purely meant for testing, not for playing with in a pack.

**Comment by KindarConrath** [comment]
Noted, thanks!
